apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: markdown-editor
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - markdown.atomsized.com
      secretName: markdown-editor-tls
  rules:
    - host: markdown.atomsized.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: markdown-editor
                port:
                  number: 80
