apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atomsized-md
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:kubeden/clopus-preview-environments.git
    targetRevision: main
    path: infrastructure/applications/atomsized.com/markdown-editor/main-app
  destination:
    server: https://kubernetes.default.svc
    namespace: atomsized
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
